name: 🚀 Test App Build

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: '🔒 Create .env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: 🔨 Build Project
        run: |
          yarn
          yarn format
          yarn lint
          yarn build
